// AUTO-GENERATED by scripts/gen-site.mjs for Led Electric LLC — do not edit by hand.
import type { SiteContent, ThemeName } from "./types";

export const site: SiteContent = {
  "business": {
    "name": "Led Electric LLC",
    "phone": "(419) 944-8509",
    "phoneHref": "tel:4199448509",
    "licenseLine": "© 2026 Led Electric LLC. Licensed, insured & locally owned.",
    "emergency": {
      "enabled": true,
      "label": "24/7 Emergency Service Available",
      "cta": {
        "label": "Request Service",
        "href": "#contact"
      }
    }
  },
  "nav": [
    {
      "label": "Services",
      "href": "#services"
    },
    {
      "label": "Service Areas",
      "href": "#areas"
    },
    {
      "label": "About",
      "href": "#about"
    },
    {
      "label": "Reviews",
      "href": "#reviews"
    },
    {
      "label": "Contact",
      "href": "#contact"
    }
  ],
  "primaryCta": {
    "label": "Call Now",
    "href": "tel:4199448509"
  },
  "hero": {
    "eyebrow": "Licensed Electricians · Toledo, OH",
    "title": "Led Electric LLC",
    "accentLine": "Trusted Toledo, OH Electrician",
    "lede": "Led Electric LLC provides licensed, insured electrician service for Toledo, OH and the surrounding area. Rated 4.9★ across 87+ Google reviews.",
    "primaryCta": {
      "label": "Book Online",
      "href": "#contact"
    },
    "ghostCta": {
      "label": "Call (419) 944-8509",
      "href": "tel:4199448509"
    },
    "imageCaption": "Your work-van photo goes here",
    "imageSrc": "https://lh3.googleusercontent.com/place-photos/AJRVUZO-tX7NSG1KM2q-EmyVCfphiXpPCXmNBk41CI-y6QC1xLORiIFmrwlutZco2hpsDZE7SBi5i__T5w4D-1CIAoEN3yYZ-15xBle2IR4Pt48EsKgDxZQ2kWplgaV5i8NePlS6PM9WiLgoEm6TG14=s4800-w1600",
    "benefits": [
      {
        "icon": "shield",
        "title": "Licensed & Insured",
        "sub": "Fully covered"
      },
      {
        "icon": "star",
        "title": "4.9★ Rated",
        "sub": "87 Google reviews"
      },
      {
        "icon": "bolt",
        "title": "24/7 Emergency",
        "sub": "Always on call"
      },
      {
        "icon": "lightbulb",
        "title": "Locally Owned",
        "sub": "Toledo-based"
      }
    ]
  },
  "stats": [
    {
      "icon": "star",
      "value": "4.9",
      "label": "Google Rating"
    },
    {
      "icon": "check",
      "value": "87+",
      "label": "Google Reviews"
    },
    {
      "icon": "bolt",
      "value": "24/7",
      "label": "Emergency Service"
    },
    {
      "icon": "shield",
      "value": "Licensed",
      "label": "& Insured"
    }
  ],
  "services": {
    "eyebrow": "Our Services",
    "heading": "Toledo, OH Electrical Services",
    "items": [
      {
        "slug": "panel-upgrades",
        "icon": "gauge",
        "title": "Panel Upgrades",
        "description": "100A→200A service upgrades, code-compliant and done in a day."
      },
      {
        "slug": "ev-chargers",
        "icon": "bolt",
        "title": "EV Chargers",
        "description": "Level 2 home charging stations for any electric vehicle."
      },
      {
        "slug": "rewiring",
        "icon": "wrench",
        "title": "Whole-Home Rewiring",
        "description": "Older homes brought safely up to modern code."
      },
      {
        "slug": "generators",
        "icon": "power",
        "title": "Generators",
        "description": "Standby and portable installs with transfer switches done right."
      },
      {
        "slug": "lighting",
        "icon": "lightbulb",
        "title": "Lighting & Fans",
        "description": "Recessed, pendants, ceiling fans, and outdoor lighting."
      },
      {
        "slug": "emergency",
        "icon": "bolt",
        "title": "Emergency Calls",
        "description": "Sparking outlet, outage, burning smell? Same-day response."
      }
    ]
  },
  "testimonials": {
    "eyebrow": "Reviews",
    "heading": "What Customers Say",
    "items": [
      {
        "quote": "Called on a saturday just for a minor electrical upgrade question. Said he could come out and give me a quote the next day (sunday). Had the part he needed and installed on the spot for a reasonable price. Very happy with the quick service. Thank you!",
        "author": "Joseph Leeper",
        "rating": 5
      },
      {
        "quote": "Left a mess in the basement. Leaving your garbage behind in a customers house is a huge no no. Installed conduit ABOVE window and didn't use a 90 or junction box. It looks low effort and fugly. Left several breakers in the off position, leaving a few outlets without power. They knocked the job out…",
        "author": "RLD",
        "rating": 4
      },
      {
        "quote": "We had LED Electric upgrade the service to our house. LED is very responsive from the first contact for a quote to the end of the job. Good communication throughout the process. They made a couple of awesome recommendations to include a cost-effective generator connection to the house and meter…",
        "author": "John Fannin",
        "rating": 5
      },
      {
        "quote": "We needed a new meter socket among other things at our house. We got 3 other estimates from other companies. The other 2 companies took forever to give us an estimate, which were both outrageous in price. Ryan, and his team on the other hand did the exact opposite. Gave us an estimate day of, a…",
        "author": "Jacob Scally",
        "rating": 5
      },
      {
        "quote": "Highly recommend LED Electric, Ryan was very professional and informative and reasonably priced. When completed updating / replacing switch board and installing ground rod, everything was labeled and made sure all the lights were working. I was text when he was on his way and when he had arrived…",
        "author": "Laura Sparks",
        "rating": 5
      }
    ]
  },
  "serviceAreas": {
    "eyebrow": "We Serve",
    "cities": [
      "Toledo"
    ]
  },
  "finalCta": {
    "heading": "Need an electrician in Toledo, OH?",
    "lede": "Call Led Electric LLC or request service online — licensed, insured, and ready to help.",
    "cta": {
      "label": "Request Service",
      "href": "#contact"
    }
  },
  "footer": {
    "columns": [
      {
        "title": "Services",
        "links": [
          {
            "label": "Panel Upgrades",
            "href": "#services"
          },
          {
            "label": "EV Chargers",
            "href": "#services"
          },
          {
            "label": "Whole-Home Rewiring",
            "href": "#services"
          },
          {
            "label": "Generators",
            "href": "#services"
          }
        ]
      },
      {
        "title": "Company",
        "links": [
          {
            "label": "About",
            "href": "#about"
          },
          {
            "label": "Reviews",
            "href": "#reviews"
          },
          {
            "label": "Service Areas",
            "href": "#areas"
          },
          {
            "label": "Contact",
            "href": "#contact"
          }
        ]
      },
      {
        "title": "Legal",
        "links": [
          {
            "label": "Privacy Policy",
            "href": "#"
          },
          {
            "label": "Terms of Service",
            "href": "#"
          },
          {
            "label": "Accessibility",
            "href": "#"
          }
        ]
      }
    ],
    "finePrint": "© 2026 Led Electric LLC. Licensed, insured & locally owned. Serving Toledo, OH."
  }
};

export const theme: ThemeName = "electric";
